#!/usr/bin/env bash

# see: https://zdoom.org/wiki/Command_line_parameters

gzdoom \
  -config ./gzdoom.ini \
  -iwad ./iwads/doom_complete.pk3 \
  -file \
    ./gfx/beautiful-doom/Beautiful_Doom_716.pk3 \
    ./sfx/idkfa-soundtrack/IDKFAv2.wad \
