#!/usr/bin/env bash

gzdoom \
  -config ./gzdoom-portable.ini \
  -file ./idkfa-soundtrack/IDKFAv2.wad \
    ./beautiful-doom/Beautiful_Doom_716.pk3 \
#    ./wads/av.zip
#    ./wads/scythex.zip
#  ./brutal-community/brutalv21.10.1.pk3
#  ./smooth-doom/SmoothDoom.pk3
