#!/usr/bin/env bash

# see: https://zdoom.org/wiki/Command_line_parameters

gzdoom \
  -skill 3\
  -warp 1 \
  -config ./gzdoom.ini \
  -iwad ./iwads/doom2.wad \
  -file \
    ./wads/infra02.pk3 \
    ./gfx/beautiful-doom/Beautiful_Doom_716.pk3 \
